name: Java Code Style Checker

on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'

jobs:
  checkstyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 14.0.2
          architecture: x64
      - name: Check style
        run: mvn -B checkstyle:check --file pom.xml
      - name: Run tests
        run: mvn -B test --file pom.xml
  codeql:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: ${{ matrix.language }}

    - name: Build
      run: |
        mvn --file pom.xml \
        clean \
        dependency:copy-dependencies \
        compile


    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1

